### ISSUE TITLE
How to show Toaster on controller load in Angular js

### ISSUE THREAD

**Issue by saineshwar** [jirikavi/AngularJS-Toaster#204] opened 2016-04-18 10:28 UTC
angular.module('main', ['ngAnimate', 'toaster'])

.controller('myController', function($scope, toaster, $window) {
    
      $scope.bar = 'Hi';
    
    // for Executing this Script on Load of Controller i have wrote here but it do not display
      var pop = {};
        toaster.success({title: "title", body:"text1"});
        toaster.error("title", "text2");
        toaster.pop({type: 'wait', title: "title", body:"text"});
        toaster.pop('success', "title", '<ul><li>Render html</li></ul>', 5000, 'trustedHtml');
        toaster.pop('error', "title", '<ul><li>Render html</li></ul>', null, 'trustedHtml');
        toaster.pop('wait', "title", null, null, 'template');

    $scope.pop = function(){
        toaster.success({title: "title", body:"text1"});
        toaster.error("title", "text2");
        toaster.pop({type: 'wait', title: "title", body:"text"});
        toaster.pop('success', "title", '<ul><li>Render html</li></ul>', 5000, 'trustedHtml');
        toaster.pop('error', "title", '<ul><li>Render html</li></ul>', null, 'trustedHtml');
        toaster.pop('wait', "title", null, null, 'template');
        toaster.pop('warning', "title", "myTemplate.html", null, 'template');
        toaster.pop('note', "title", "text");
        toaster.pop('success', "title", 'Its address is https://google.com.', 5000, 'trustedHtml', function(toaster) {
            var match = toaster.body.match(/http[s]?:\/\/[^\s]+/);
            if (match) $window.open(match[0]);
            return true;
        });
        toaster.pop('warning', "Hi ", "{template: 'myTemplateWithData.html', data: 'MyData'}", 15000, 'templateWithData');
    };
    
    $scope.goToLink = function(toaster) {
      var match = toaster.body.match(/http[s]?:\/\/[^\s]+/);
      if (match) $window.open(match[0]);
      return true;
    };
    
    $scope.clear = function(){
        toaster.clear();
    };
});

**Comment by Stabzs** [comment] 2016-04-18 12:32
How and where did you include the container) are you certain your controller is loaded into the DOM? You'll need to provide additional details please.

**Comment by saineshwar** [comment] 2016-04-18 13:02
what container you are asking stabzs sir ?

**Comment by Stabzs** [comment] 2016-04-18 15:08
If you do not have a `<toaster-container></toaster-container>` element in your DOM (and it should be outside of your routing) there will be nothing for the toasts to be rendered in.

Please see https://github.com/jirikavi/AngularJS-Toaster#getting-started

**Comment by Stabzs** [comment] 2016-04-18 19:41
I'm closing this since it is not a bug. That's said if you need further assistance feel free continue to post and I'll guide you as best I can.

**Closed by Stabzs** 2016-04-18 19:41 UTC
Labels: invalid, question
