### ISSUE TITLE
how to specify show location in config

### ISSUE THREAD

**Issue by MisterChangRay** [jirikavi/AngularJS-Toaster#214] opened 2016-06-21 01:51 UTC
angular config, 
 $scope.pop({
                    type: 'error',
                    title: 'test：',
                    bodyOutputType : 'trustedHtml',
                    body: html,
                    timeout: 10000,
                    showCloseButton: true,
                    'position-class': 'toast-top-left'  // this is invalid
                })

**Comment by Stabzs** [comment] 2016-06-21 02:00
Closed as duplicate of https://github.com/jirikavi/AngularJS-Toaster/issues/212

**Closed** 2016-06-21 02:01 UTC
