### ISSUE TITLE
Icon-class will not change

### ISSUE THREAD

**Issue by cvaught001** [jirikavi/AngularJS-Toaster#144] opened 2015-07-22 22:05 UTC
Had a few minutes to look at this today.  'icon-class': will not change.
 toaster.pop(  {
                            type: 'info',
                            title: 'No Data In Range',                           
                            body: 'The date range you selected, returns no recordset.',
                            show
});
    type: 'info', 
I can see the toast.type change my Parameter in the console.log

It alway's renders the toasterConfig regardless of what value I populate.

This should really be fixed...

**Comment by Stabzs** [comment] 2015-07-23 03:42
I don't believe that this is actually a bug, but rather a "feature", if you will.  It was implemented at least back as far as version 0.4.2 and is probably an original port from toastr, since that is a toastr feature.

Currently, it works as a fallback.  If the type is not found in the icon-classes array, icon-class is the fallback type, which per the config is always 'info'.

On the other hand, it's possible that what you're looking for is the same type of functionality in #61, which could certainly be implemented.  If this is what you are looking for, please close this issue and +1 on that issue.

**Comment by cvaught001** [comment] 2015-07-23 15:21
Thanks Stabzs.. The functionality shown in #61 is highly desire able and should be part of this project.

**Comment by Stabzs** [comment] 2015-07-23 15:46
Closing this as a duplicate of #61.

**Closed by Stabzs** 2015-07-23 15:46 UTC
