### ISSUE TITLE
A few traps I encountered with this library

### ISSUE THREAD

**Issue by davidmiani** [jirikavi/AngularJS-Toaster#194] opened 2016-02-10 05:48 UTC
While integrating this library into my site, I hit a couple of minor problems that took a while to fix, but weren't really bugs in the library. It would be nice to either document these or to throw an error if the situation can be detected by the library.

1. When binding to a directive, if the element has a `restrict: 'E'` property then it will silently be ignored and use the default template. Ideally either it would work or an error should be thrown.This appears to be intentional based on the directive binding tests, but is still pretty surprising and very hard to debug.
2. If the directive has a isolated scope, then `directiveData` won't get passed through. E.g. `scope: { directiveData: '=' }` won't work, and directiveData will always be undefined.
3. When used with an ionic dialog, the clicking the notifications won't do anything. This is because ionic dialog adds a `pointer-events: none` to the body, and `pointer-events: auto` to the dialog. However as the notifications appear on top of the dialog correctly (the z-index is high enough), this is a bit confusing. I'm guessing other modal style libraries would have a similar problem. I think either note this problem in the documentation, or add `pointer-events: auto` to the `#toast-container` css. I can't see why anyone would want pointer events disabled for toasts, so I think adding the css is a pretty safe option.

**Comment by Stabzs** [comment] 2016-02-10 20:23
Thanks for the thoughtful feedback!  It's always appreciated.

1. I understand your point here and it is a good one.  Part of the issue is the fact that the directive is compiled inline as an attribute directive.  As a result, an element restricted directive will fail silently inside of AngularJS, not the Toaster library, which makes it a bit harder to track and throw an error for.  There are some potential solutions to this...requiring the directive type attribute to be passed, identifying if the directiveName argument begins with a `<`, indicating that it would be an element-type directive, or simply attempting to compile the directiveName as an element first and retrying as an attribute if that fails.  Unfortunately, Angular 1 makes these types of things a bit trickier, but this could certainly be changed to be more resilient and helpful.

2. directiveData was designed to be the ONLY mode for transporting data across to rendered directive.  As a result, you are correct, if using isolated scope the directive would create it's own isolated scope, preventing it from accepting the directiveData argument from the parent. 

In order to be added to the isolated scope, it would need to be inlined as an attribute argument and passed across.  I suppose another potential solution would be to compile and check for the presence of isolatedScope.  If it exists, the directiveData could be added directly to the isolatedScope itself.  It's a bit of a hack but it would prevent needing to inline the argument as an attribute to be added during $compile.

This should probably either be documented or the method for passing data should be redesigned.  However, if the argument is no longer used, this makes it harder to dynamically inject data into the directive from the source that pops the toast, which is why this approach was chosen.  I'm completely open to suggestions here since I'd like to make the directive feature as useful as possible since it's really powerful as is already and any improvements would be fantastic.

3. That's a very odd problem and a clever solution.  I can't imagine that adding `pointer-events:auto` to the container's css would in any way compromise the functionality or that it would result in undesirable behavior.

**Comment by davidmiani** [comment] 2016-02-10 21:03
What you wrote for 1 and 2 makes perfect sense, so I don't think it would be a good idea to change that behaviour. You're right that you don't need an isolated scope for your notification directives. It is just that as 95% of my directives do use an isolated scope, so I'm in a habit of putting that line in.

So just checking for the error seems like the best way. This could be done with $injector service, e.g:

```
function checkDirectiveIsValidForNotifications($injector, htmlDirectiveName) {
  var directiveServiceName = angular.element.camelCase(htmlDirectiveName) + "Directive";
  var directiveDetailResults = $injector.get(directiveServiceName);
  if (directiveDetailResults .length == 0) {
    throw new Error("Could not find directive " + htmlDirectiveName + " for use in notification");
  }
  var directiveDetails = directiveDetailResults[0];
  if (directiveDetails.scope !== true && directiveDetails.scope) {
    throw new Error("Cannot use a directive in a notification with an isolated scope. " + 
                               "The scope must be either true or falsy (e.g. false/null/undefined)" + 
                               "Occurred for directive " + htmlDirectiveName);
  }
  if (!directiveDetails.restrict.includes("A")) {
    throw new Error("Directives used in notifications must be usable as attributes " +
                              "Add 'A' to the restrict option (or remove the option entirely). Occurred for directive " + htmlDirectiveName);
  }
}
```

**Comment by Stabzs** [comment] 2016-02-10 21:29
These are really reasonable checks and they coincide with the checking for the existence of the directive already.  I'll be happy to get these added and merged in in the near future with additional explanations in the documentation.  Again, thanks for the input.  It's greatly appreciated.

**Closed** 2016-02-18 19:59 UTC
