### ISSUE TITLE
Ability to retrieve and manipulate toasts

### ISSUE THREAD

**Issue by hanthomas** [jirikavi/AngularJS-Toaster#58] opened 2014-10-27 19:33 UTC
It would be great if we could access an existing toast by ID, like the way KayHadrin implemented it in his/her fork.  Thanks!

**Comment by RichardJECooke** [comment] 2015-01-07 12:50
Hi. Did you find a way to do this?  I'd love to be able close a specific toast - like you can in normal toastr 'Close last toast' : http://codeseven.github.io/toastr/demo.html

**Comment by triberraar** [comment] 2016-03-04 19:03
Hej,
I was able to close a specific toast by doing this when spawning:

     toaster.pop({
		type: 'error',
		body: 'Login failed, please correct the login form and try again.',
		toastId: 'loginFailedToastId',
		timeout: 0
    });

and them close it by calling:
    toaster.clear(undefined, 'loginFailedToastId');

seems you can also define a toasterId, i guess that is like a grouping parameter for toasts and the first parameter to clear is this toaster id. though i haven't checked that.
Hope this helps

**Comment by phillipgreenii** [comment] 2016-03-18 14:19
I noticed that `toaster.pop()` doesn't return anything, could we change that to return some kind of handle to the specific toaster message?  Then you could close specific toast messages programmatically?

```javascript
var handler = toaster.pop('close me!');
handler.clear();
```

**Comment by triberraar** [comment] 2016-03-18 14:48
I think returning the toastId instead of passing it would indeed be better.

**Comment by Stabzs** [comment] 2016-03-18 15:00
@phillipgreenii and @triberraar this is the exact issue I've been struggling with for a while and haven't decided the best way to solve it yet.

Because all toast pop calls are brokered through toasterEventRegistry per container, the issue is that pop calls are actually broadcasted to ALL toaster containers, even if targeted by toasterId.  Once receives, the container checks for the presence of the id and acts accordingly.

The issue is returning that response back up and/or waiting until all responses are retrieved.  For instance, if you pop and it targets two containers, you would actually need two responses and, even more confusing, they might even have the same toast id.

I'm open to suggestions on how to work around this since I feel like it's a design flaw and it makes the library less usable.  (It's worth noting that any forks that return back out an object have not solved for multiple containers).

**Comment by phillipgreenii** [comment] 2016-03-18 16:23
I have not worked with multiple containers, but it is my understanding that a single toaster message generated from a single call to `pop` can only be associated with a single toaster container.  So, the object returned from the pop would need to have knowledge of both the specified container as well as the specified message id.  Isn't that enough to do a clear?

So in my example:
```javascript
var handler = toaster.pop('close me!'); 

handler.clear(); 
```

A very simplistic implementation might look like:
```javascript

function($rootScope, toasterConfig) {
    this.pop = function(type, title, body, timeout, bodyOutputType, clickHandler, toasterId, showCloseButton, toastId, onHideCallback) {
        // current implementation stays the same
        // but not displayed for this example to save space
        $rootScope.$emit('toaster-newToast', toasterId, toastId);
        // new code starts here
        var toast = this;
        handler = {
            clear: function() {
                toast.clear(toasterId, toastId);
            }
        }
        return handler;
    };

    this.clear = function(toasterId, toastId) {
        $rootScope.$emit('toaster-clearToasts', toasterId, toastId);
    };

}
```

**Comment by Stabzs** [comment] 2016-03-18 16:48
@phillipgreenii  That understanding is incorrect.  By default, if a toasterid is not defined on the toaster containers and not provided explicitly in the toast message, by default the toast would be added to any toaster-containers that could be broadcasted to.

The scenario you've described works fine for clearing when the toastid is described ahead of time.  However, in the scenario where the toastId is automatically incremented and generated within a specific container, it wouldn't work as described.  What "MIGHT" work however would be overriding the clear handler within a container itself, although that still is not being bubbled up through the event.

Finally, keep in mind that this doesn't solve the "retrieve a toast instance" scenario, nor does it properly account for scenarios where toast ids and toasterids are not known beforehand and broadcasts are reaching all available containers.

**Comment by phillipgreenii** [comment] 2016-03-18 20:45
@Stabzs Thanks for the clarification.  At closer inspection, I'm only interested in a subset of this issue.  I don't need to have access to the toast message itself; I would only like to be able to clear a specific message in a fashion I mentioned previously.  In my scenario, I think the code I had before works just fine.  If there are multiple containers that accept the toast message, then they would both be cleared.  This is the same behavior as using `toaster.clear()`, so this is really nothing more than a convenience wrapper.  Should I open a separate issue?

**Comment by Stabzs** [comment] 2016-03-20 13:16
@phillipgreenii since it's not exactly able to close this issue in entirety, that's probably best, even though it's related.

The code you've described only works in the case where there is a toastid to capture.  If there isn't, a clear handler couldn't be attached, else it would close all toasts which would be misleading, since you would expect the handler from a pop instance to only close that instance.  Other than that, yes, such a wrapper is perfectly reasonable, albeit a bit limited in it's use I think.

**Comment by Stabzs** [comment] 2016-04-12 19:39
Release https://github.com/jirikavi/AngularJS-Toaster/releases/tag/2.0.0 has been merged and published to npm.

**Closed** 2016-04-12 23:48 UTC
