### ISSUE TITLE
problem with toast

### ISSUE THREAD

**Issue by INGCRENGIFO** [jirikavi/AngularJS-Toaster#140] opened 2015-07-02 13:46 UTC
The message of toast always appears on the right and not the left as shown in the documentation, I have code like the example given, that I missing?
http://subefotos.com/ver/?2d374c855acea1bf04f275b0ce52ecf5o.png

**Comment by Stabzs** [comment] 2015-07-02 13:49
Can you please create a small PoC illustrating this problem?  It looks like a styling issue.  Are you applying any custom layouts or styles?

**Comment by INGCRENGIFO** [comment] 2015-07-02 14:14
no, use the original css, I make no change
"HTML"
<toaster-container toaster-options="{'time-out': 3000, 'close-button':true, 'animation-class': 'toast-top-center'}"></toaster-container>
"JS"
toaster.success({title: "title", body:"text1"});

**Comment by Stabzs** [comment] 2015-07-02 14:43
Using the supplied toaster-container and js call, I cannot reproduce this issue.  What browser is this in?   Can you provide a full gist example of all the code required to reproduce this issue?  In addition, please make sure that you do not have a caching issue.

**Comment by INGCRENGIFO** [comment] 2015-07-02 14:53
I did hesitate, that has to do the caching? I keep it in a local data storage token, it affects something?

**Comment by Stabzs** [comment] 2015-07-02 14:55
You may need to clear your browser's cache if you've made changes. And no, local storage should not cause something like this.

 That said, there's no way for me to currently reproduce this issue with what you've shown.  Please create a gist https://gist.github.com/ of the pertinent code that demonstrates this issue.

**Comment by INGCRENGIFO** [comment] 2015-07-02 15:02
https://gist.github.com/INGCRENGIFO/4b54752acc4a190cf49c

**Comment by INGCRENGIFO** [comment] 2015-07-02 15:03
the code is large and fails if I stick, and if I give access to my desk to see everything working ??

**Comment by Stabzs** [comment] 2015-07-02 15:54
I don't need all your code, I only need a small sample that illustrates the problem you've described.  At this point it looks like a configuration or styling issue, not an issue with the library itself.

**Comment by INGCRENGIFO** [comment] 2015-07-02 16:02
and I've pasted the code that you request, you can check, but I'm not wearing styles, use the same library

**Comment by Stabzs** [comment] 2015-07-02 16:14
This is not a reproducible sample however.  I can't paste this into a file and create a reproducible example with what you've shown.

**Comment by INGCRENGIFO** [comment] 2015-07-02 16:17
why? I miss me? I'm reviewing and appears to have an error materializecss compatibility library, do not know how to avoid that.

**Comment by INGCRENGIFO** [comment] 2015-07-02 16:33
effectively substantiate that materializecss library causes the problem, delete the css of that library all "toast" and worked, and unfortunately will not be able to use the CDN.

You know what the difference between
https://github.com/jirikavi/AngularJS-Toaster
and
https://github.com/Foxandxss/angular-toastr
and
https://github.com/CodeSeven/toastr

I see the same

**Comment by Stabzs** [comment] 2015-07-02 16:44
Glad to hear that you found your issue.

https://github.com/jirikavi/AngularJS-Toaster (this repository) is an AngularJS port of https://github.com/CodeSeven/toastr that has continued to grow in it's own way.  Foxandxss is another AngularJS port of the CodeSeven toastr library that has gone a different route.  Since it seems like this is not an issue with this library, I'm closing this issue.

**Comment by INGCRENGIFO** [comment] 2015-07-02 16:45
Thank You So Much

**Closed by Stabzs** 2015-07-02 16:44 UTC
